import { expect, test } from '@playwright/test';
test('loads, lifts, moves, brakes, switches cameras and survives pause', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto('/'); await page.getByRole('button', { name: 'Begin expedition' }).click();
  const telemetry = page.getByTestId('flight-telemetry');
  await page.keyboard.press('Space'); await expect(telemetry).toHaveAttribute('data-flying', 'true');
  await page.keyboard.down('KeyW'); await page.waitForTimeout(1000); await page.keyboard.up('KeyW');
  const traveled = JSON.parse((await telemetry.getAttribute('data-position'))!);
  expect(traveled[2]).toBeLessThan(64);
  await page.waitForTimeout(1300); expect(Number(await telemetry.getAttribute('data-speed'))).toBeLessThan(.5);
  await page.keyboard.press('Escape'); await expect(page.getByRole('heading', { name: 'Take your time.' })).toBeVisible();
  await page.getByRole('button', { name: 'Adjust flight settings' }).click();
  await page.getByRole('button', { name: 'First person', exact: true }).click();
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await expect(telemetry).toHaveAttribute('data-flying', 'true');
  await page.waitForTimeout(500);
  const resumed = JSON.parse((await telemetry.getAttribute('data-position'))!);
  expect(Math.abs(resumed[2] - traveled[2])).toBeLessThan(3);
  await page.getByRole('button', { name: 'Flight settings' }).click();
  await expect(page.getByRole('button', { name: 'First person', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Return to arrival terrace' }).click();
  await expect(telemetry).toHaveAttribute('data-flying', 'false');
  expect(errors).toEqual([]);
});
test('portrait/landscape resize retains position and text route works', async ({ page }) => {
  await page.setViewportSize({ width: 393, height: 852 });
  await page.goto('/'); await page.getByRole('button', { name: 'Begin expedition' }).click();
  await page.keyboard.press('Space'); await page.waitForTimeout(800);
  const telemetry = page.getByTestId('flight-telemetry');
  const before = JSON.parse((await telemetry.getAttribute('data-position'))!);
  await page.setViewportSize({ width: 852, height: 393 }); await page.waitForTimeout(500);
  const after = JSON.parse((await telemetry.getAttribute('data-position'))!);
  expect(Math.hypot(...after.map((v: number, i: number) => v - before[i]))).toBeLessThan(.4);
  await page.getByRole('button', { name: 'Field guide', exact: true }).click();
  await page.getByRole('button', { name: 'Recover municipal record' }).click();
  await expect(page.getByText('The last ordinary morning', { exact: true })).toBeVisible();
  await expect(page.getByText('Original fiction', { exact: true })).toBeVisible();
});
